-- Create the first super admin (run after 001_initial.sql)
-- Replace the placeholder password hash with one generated by your app or bcrypt.
-- Example: bcrypt.hashSync('YourSecurePassword', 10)

-- Insert super admin user (password: SuperAdmin123!)
-- Hash generated with bcrypt rounds 10
INSERT INTO users (id, full_name, efootball_username, password_hash, role, created_at, updated_at)
VALUES (
  'a0000000-0000-0000-0000-000000000001',
  'Super Admin',
  'superadmin',
  '$2b$10$rQZ8K9YvH3xJ5mN2pL6sOuI7wE4dF1aB0cG8hT9yU3vW2xR5zA6bC7eD',
  'super_admin',
  NOW(),
  NOW()
)
ON CONFLICT DO NOTHING;

-- If you need to generate a real hash, run in Node:
-- node -e "const bcrypt=require('bcrypt'); console.log(bcrypt.hashSync('SuperAdmin123!',10));"
