-- Create the first super admin (run after 001_initial.sql)
-- Replace the placeholder password hash with one generated by your app or bcrypt.
-- Example: bcrypt.hashSync('YourSecurePassword', 10)

-- Insert super admin user (password: Sp@xx1fy)
-- Hash generated with bcrypt rounds 10
INSERT INTO users (id, full_name, efootball_username, password_hash, role, created_at, updated_at)
VALUES (
  'a0000000-0000-0000-0000-000000000001',
  'Super Admin',
  'migichi47',
  '$2b$10$0jJ/g/QPI8jgGL7mMfYB6u5UtIDrS9B4c4132kryRnyyiUuOiTbE.',
  'super_admin',
  NOW(),
  NOW()
)
ON DUPLICATE KEY UPDATE id = id;

-- If you need to generate a real hash, run in Node:
-- node -e "const bcrypt=require('bcrypt'); console.log(bcrypt.hashSync('SuperAdmin123!',10));"
